# Generated by Django 4.2.1 on 2023-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.IntegerField()),
                ('size_code', models.CharField(max_length=120)),
                ('sort_order', models.CharField(max_length=120)),
            ],
        ),
    ]
