# Generated by Django 4.2.1 on 2023-06-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_id', models.IntegerField()),
                ('other_data', models.CharField(max_length=120)),
                ('Apparel_sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.apparel_size')),
            ],
        ),
    ]
