# Generated by Django 4.2.1 on 2023-06-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorid', models.IntegerField()),
                ('color_code', models.CharField(max_length=120)),
                ('color_name', models.CharField(max_length=120)),
                ('Productcolour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_colour')),
            ],
        ),
    ]
